### ISSUE TITLE
在群晖ssh中运行报错

### ISSUE THREAD

**Issue by iKumaDev** [TreviD/aliddns#12]
Traceback (most recent call last):
  File "./aliddns.py", line 321, in <module>
    recordListInfo = get_record_info(RR, DomainName, Type)
  File "./aliddns.py", line 91, in get_record_info
    context = ssl._create_unverified_context()
AttributeError: 'module' object has no attribute '_create_unverified_context'

问一下如何解决

**Comment by TreviD** [comment]
python版本是什么？建议升级一下python3最新版本

**Comment by iKumaDev** [comment]
是套件中心的3.4.1-0032
