### ISSUE TITLE
win10系统无法解析主域名

### ISSUE THREAD

**Issue by slaners** [TreviD/aliddns#2]
设置aliddnsipv6_name1= '@'  
cmd执行之后会有报错，python版本为3.8.0
报错信息
Traceback (most recent call last):
  File "C:\aliddns.py", line 197, in <module>
    add_record(ipv6Addr)
  File "C:\aliddns.py", line 173, in add_record
    send_request("AddDomainRecord&DomainName=" + aliddnsipv6_domain, urlParam)
  File "C:\aliddns.py", line 134, in send_request
    jsonStr = urllib.request.urlopen(url).read().decode("utf8")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by TreviD** [comment]
已更新
